import {
  AdventoreIcon,
  AmountOfEarlyRisingSvg,
  BackgammonIcon,
  BackpackingIcon,
  bicycle,
  BoatIcon,
  BodybuildingIcon,
  CaffeIcon,
  CampingIcon,
  CanaryIcon,
  CatIcon,
  CaveIcon,
  ClimbingIcon,
  ConcertIcon,
  CulturalExchangeIcon,
  CulturalIcon,
  DesignIcon,
  DogIcon,
  EthnologyIcon,
  ExplorationIcon,
  FastFoodIcon,
  FestivalsIcon,
  FishIcon,
  FishingIcon,
  FoodIcon,
  GameIcon,
  GardeningIcon,
  Gender,
  GroupGameIcon,
  HamsterIcon,
  HistoricalPlacesIcon,
  HorseIcon,
  HumoristIcon,
  KarateIcon,
  LionIcon,
  Marital,
  MarketsIcon,
  MeatIcon,
  MonkeyIcon,
  MosqueIcon,
  MovieIcon,
  MuseamIcon,
  MusicIcon,
  NatureIcon,
  NatureTourIcon,
  OffroadIcon,
  ParagliderIcon,
  ParkIcon,
  ParrotIcon,
  PlayingIcon,
  PotteryIcon,
  RabbitIcon,
  RestaurantIcon,
  SeeBeach,
  ShipIcon,
  ShootingIcon,
  ShopIcon,
  SingerIcon,
  SkateIcon,
  SkiingIcon,
  Smoke,
  SoccerIcon,
  Spirit,
  Sport,
  SquashIcon,
  SquirrelIcon,
  SwimmingIcon,
  TheaterIcon,
  TrainIcon,
  TravelingByShipIcon,
  VegetarianIcon,
  VillageTourIcon,
  WalkingIcon,
  WildlifeIcon,
  WineIcon,
  WritingIcon,
} from './icons';

export const allIcon = [
  { title: 'البرز', flag: '🇮🇷' },
  { title: 'اردبیل', flag: '🇮🇷' },
  { title: 'ایلام', flag: '🇮🇷' },
  { title: 'اصفهان', flag: '🇮🇷' },
  { title: 'آذربایجان غربی', flag: '🇮🇷' },
  { title: 'آذربایجان شرقی', flag: '🇮🇷' },
  { title: 'بوشهر', flag: '🇮🇷' },
  { title: 'تهران', flag: '🇮🇷' },
  { title: 'چهار محال و بختیاری', flag: '🇮🇷' },
  { title: 'خراسان جنوبی', flag: '🇮🇷' },
  { title: 'خراسان رضوی', flag: '🇮🇷' },
  { title: 'خراسان شمالی', flag: '🇮🇷' },
  { title: 'خوزستان', flag: '🇮🇷' },
  { title: 'زنجان', flag: '🇮🇷' },
  { title: 'سمنان', flag: '🇮🇷' },
  { title: 'سیستان و بلوچستان', flag: '🇮🇷' },
  { title: 'فارس', flag: '🇮🇷' },
  { title: 'قزوین', flag: '🇮🇷' },
  { title: 'قم', flag: '🇮🇷' },
  { title: 'کردستان', flag: '🇮🇷' },
  { title: 'کرمان', flag: '🇮🇷' },
  { title: 'کرمانشاه', flag: '🇮🇷' },
  { title: 'کهکیلویه و بویراحمد', flag: '🇮🇷' },
  { title: 'گلستان', flag: '🇮🇷' },
  { title: 'گیلان', flag: '🇮🇷' },
  { title: 'لرستان', flag: '🇮🇷' },
  { title: 'مازندران', flag: '🇮🇷' },
  { title: 'مرکزی', flag: '🇮🇷' },
  { title: 'هرمزگان', flag: '🇮🇷' },
  { title: 'همدان', flag: '🇮🇷' },
  { title: 'یزد', flag: '🇮🇷' },
  { title: 'افغانستان', flag: '🇦🇫' },
  { title: 'آلبانی', flag: '🇦🇱' },
  { title: 'الجزایر', flag: '🇩🇿' },
  { title: 'آندورا', flag: '🇦🇩' },
  { title: 'آنگولا', flag: '🇦🇴' },
  { title: 'آنتیگوا و باربودا', flag: '🇦🇬' },
  { title: 'آرژانتین', flag: '🇦🇷' },
  { title: 'ارمنستان', flag: '🇦🇲' },
  { title: 'استرالیا', flag: '🇦🇺' },
  { title: 'اتریش', flag: '🇦🇹' },
  { title: 'آذربایجان', flag: '🇦🇿' },
  { title: 'باهاما', flag: '🇧🇸' },
  { title: 'بحرین', flag: '🇧🇭' },
  { title: 'بنگلادش', flag: '🇧🇩' },
  { title: 'باربادوس', flag: '🇧🇧' },
  { title: 'بلاروس', flag: '🇧🇾' },
  { title: 'بلژیک', flag: '🇧🇪' },
  { title: 'بلیز', flag: '🇧🇿' },
  { title: 'بنین', flag: '🇧🇯' },
  { title: 'بوتان', flag: '🇧🇹' },
  { title: 'بولیوی', flag: '🇧🇴' },
  { title: 'بوسنی و هرزگوین', flag: '🇧🇦' },
  { title: 'بوتسوانا', flag: '🇧🇼' },
  { title: 'برزیل', flag: '🇧🇷' },
  { title: 'برونئی', flag: '🇧🇳' },
  { title: 'بلغارستان', flag: '🇧🇬' },
  { title: 'بورکینافاسو', flag: '🇧🇫' },
  { title: 'بوروندی', flag: '🇧🇮' },
  { title: 'کیپ ورد', flag: '🇨🇻' },
  { title: 'کامبوج', flag: '🇰🇭' },
  { title: 'کامرون', flag: '🇨🇲' },
  { title: 'کانادا', flag: '🇨🇦' },
  { title: 'جمهوری آفریقای مرکزی', flag: '🇨🇫' },
  { title: 'چاد', flag: '🇹🇩' },
  { title: 'شیلی', flag: '🇨🇱' },
  { title: 'چین', flag: '🇨🇳' },
  { title: 'کلمبیا', flag: '🇨🇴' },
  { title: 'کومور', flag: '🇰🇲' },
  { title: 'کنگو (برازاویل)', flag: '🇨🇬' },
  { title: 'کاستاریکا', flag: '🇨🇷' },
  { title: 'کرواسی', flag: '🇭🇷' },
  { title: 'کوبا', flag: '🇨🇺' },
  { title: 'قبرس', flag: '🇨🇾' },
  { title: 'چک', flag: '🇨🇿' },
  { title: 'دانمارک', flag: '🇩🇰' },
  { title: 'جیبوتی', flag: '🇩🇯' },
  { title: 'دومینیکا', flag: '🇩🇲' },
  { title: 'جمهوری دومینیکن', flag: '🇩🇴' },
  { title: 'اکوادور', flag: '🇪🇨' },
  { title: 'مصر', flag: '🇪🇬' },
  { title: 'السالوادور', flag: '🇸🇻' },
  { title: 'گینه استوایی', flag: '🇬🇶' },
  { title: 'اریتره', flag: '🇪🇷' },
  { title: 'استونی', flag: '🇪🇪' },
  { title: 'اسواتینی', flag: '🇸🇿' },
  { title: 'اتیوپی', flag: '🇪🇹' },
  { title: 'فیجی', flag: '🇫🇯' },
  { title: 'فنلاند', flag: '🇫🇮' },
  { title: 'فرانسه', flag: '🇫🇷' },
  { title: 'گابن', flag: '🇬🇦' },
  { title: 'گامبیا', flag: '🇬🇲' },
  { title: 'گرجستان', flag: '🇬🇪' },
  { title: 'آلمان', flag: '🇩🇪' },
  { title: 'غنا', flag: '🇬🇭' },
  { title: 'یونان', flag: '🇬🇷' },
  { title: 'گرنادا', flag: '🇬🇩' },
  { title: 'گواتمالا', flag: '🇬🇹' },
  { title: 'گینه', flag: '🇬🇳' },
  { title: 'گینه بیسائو', flag: '🇬🇼' },
  { title: 'گویان', flag: '🇬🇾' },
  { title: 'هائیتی', flag: '🇭🇹' },
  { title: 'واتیکان', flag: '🇻🇦' },
  { title: 'هندوراس', flag: '🇭🇳' },
  { title: 'مجارستان', flag: '🇭🇺' },
  { title: 'ایسلند', flag: '🇮🇸' },
  { title: 'هند', flag: '🇮🇳' },
  { title: 'اندونزی', flag: '🇮🇩' },
  { title: 'عراق', flag: '🇮🇶' },
  { title: 'ایرلند', flag: '🇮🇪' },
  { title: 'اسرائیل', flag: '🇮🇱' },
  { title: 'ایتالیا', flag: '🇮🇹' },
  { title: 'جامائیکا', flag: '🇯🇲' },
  { title: 'ژاپن', flag: '🇯🇵' },
  { title: 'اردن', flag: '🇯🇴' },
  { title: 'قزاقستان', flag: '🇰🇿' },
  { title: 'کنیا', flag: '🇰🇪' },
  { title: 'کویت', flag: '🇰🇼' },
  { title: 'قرقیزستان', flag: '🇰🇬' },
  { title: 'لائوس', flag: '🇱🇦' },
  { title: 'لتونی', flag: '🇱🇻' },
  { title: 'لبنان', flag: '🇱🇧' },
  { title: 'لسوتو', flag: '🇱🇸' },
  { title: 'لیبریا', flag: '🇱🇷' },
  { title: 'لیبی', flag: '🇱🇾' },
  { title: 'لیختن اشتاین', flag: '🇱🇮' },
  { title: 'لیتوانی', flag: '🇱🇹' },
  { title: 'لوکزامبورگ', flag: '🇱🇺' },
  { title: 'ماداگاسکار', flag: '🇲🇬' },
  { title: 'مالاوی', flag: '🇲🇼' },
  { title: 'مالزی', flag: '🇲🇾' },
  { title: 'مالدیو', flag: '🇲🇻' },
  { title: 'مالی', flag: '🇲🇱' },
  { title: 'مالت', flag: '🇲🇹' },
  { title: 'مکزیک', flag: '🇲🇽' },
  { title: 'مولداوی', flag: '🇲🇩' },
  { title: 'مغولستان', flag: '🇲🇳' },
  { title: 'مونته نگرو', flag: '🇲🇪' },
  { title: 'مراکش', flag: '🇲🇦' },
  { title: 'موزامبیک', flag: '🇲🇿' },
  { title: 'میانمار', flag: '🇲🇲' },
  { title: 'نامیبیا', flag: '🇳🇦' },
  { title: 'نپال', flag: '🇳🇵' },
  { title: 'هلند', flag: '🇳🇱' },
  { title: 'نیوزیلند', flag: '🇳🇿' },
  { title: 'نیجر', flag: '🇳🇪' },
  { title: 'نیجریه', flag: '🇳🇬' },
  { title: 'کره شمالی', flag: '🇰🇵' },
  { title: 'نروژ', flag: '🇳🇴' },
  { title: 'عمان', flag: '🇴🇲' },
  { title: 'پاکستان', flag: '🇵🇰' },
  { title: 'پرو', flag: '🇵🇪' },
  { title: 'فیلیپین', flag: '🇵🇭' },
  { title: 'پرتغال', flag: '🇵🇹' },
  { title: 'قطر', flag: '🇶🇦' },
  { title: 'روسیه', flag: '🇷🇺' },
  { title: 'عربستان', flag: '🇸🇦' },
  { title: 'صربستان', flag: '🇷🇸' },
  { title: 'سوئیس', flag: '🇨🇭' },
  { title: 'سوئد', flag: '🇸🇪' },
  { title: 'ترکیه', flag: '🇹🇷' },
  { title: 'اوکراین', flag: '🇺🇦' },
  { title: 'امارات', flag: '🇦🇪' },
  { title: 'انگلستان', flag: '🇬🇧' },
  { title: 'آمریکا', flag: '🇺🇸' },
  { title: 'یمن', flag: '🇾🇪' },
  { title: 'زیمبابوه', flag: '🇿🇼' },
  { title: 'لری', flag: '🇮🇷' },
  { title: 'آفریکانس', flag: '🇿🇦' },
  { title: 'آلبانیایی', flag: '🇦🇱' },
  { title: 'امهری', flag: '🇪🇹' },
  { title: 'عربی', flag: '🇸🇦' },
  { title: 'ارمنی', flag: '🇦🇲' },
  { title: 'آذربایجانی', flag: '🇦🇿' },
  { title: 'باسکی', flag: '🇪🇸' },
  { title: 'بلاروسی', flag: '🇧🇾' },
  { title: 'بنگالی', flag: '🇧🇩' },
  { title: 'بوسنیایی', flag: '🇧🇦' },
  { title: 'بلغاری', flag: '🇧🇬' },
  { title: 'کاتالان', flag: '🇪🇸' },
  { title: 'سبوانو', flag: '🇵🇭' },
  { title: 'چینی (ساده‌شده)', flag: '🇨🇳' },
  { title: 'چینی (سنتی)', flag: '🇹🇼' },
  { title: 'کرسیکایی', flag: '🇫🇷' },
  { title: 'کرواتی', flag: '🇭🇷' },
  { title: 'چکی', flag: '🇨🇿' },
  { title: 'دانمارکی', flag: '🇩🇰' },
  { title: 'هلندی', flag: '🇳🇱' },
  { title: 'انگلیسی', flag: '🇺🇸' },
  { title: 'اسپرانتو', flag: '🌍' },
  { title: 'استونیایی', flag: '🇪🇪' },
  { title: 'فنلاندی', flag: '🇫🇮' },
  { title: 'فرانسوی', flag: '🇫🇷' },
  { title: 'گالیسی', flag: '🇪🇸' },
  { title: 'گرجی', flag: '🇬🇪' },
  { title: 'آلمانی', flag: '🇩🇪' },
  { title: 'یونانی', flag: '🇬🇷' },
  { title: 'گجراتی', flag: '🇮🇳' },
  { title: 'هائیتی', flag: '🇭🇹' },
  { title: 'هاوسی', flag: '🇳🇬' },
  { title: 'هاوایی', flag: '🇺🇸' },
  { title: 'عبری', flag: '🇮🇱' },
  { title: 'هندی', flag: '🇮🇳' },
  { title: 'همونگ', flag: '🌏' },
  { title: 'مجارستانی', flag: '🇭🇺' },
  { title: 'ایسلندی', flag: '🇮🇸' },
  { title: 'ایگبو', flag: '🇳🇬' },
  { title: 'اندونزیایی', flag: '🇮🇩' },
  { title: 'ایرلندی', flag: '🇮🇪' },
  { title: 'ایتالیایی', flag: '🇮🇹' },
  { title: 'ژاپنی', flag: '🇯🇵' },
  { title: 'جاوه‌ای', flag: '🇮🇩' },
  { title: 'کانادا', flag: '🇮🇳' },
  { title: 'قزاقی', flag: '🇰🇿' },
  { title: 'خمری', flag: '🇰🇭' },
  { title: 'کینیارواندا', flag: '🇷🇼' },
  { title: 'کره‌ای', flag: '🇰🇷' },
  { title: 'کردی (کرمانجی)', flag: '🌏' },
  { title: 'قرقیزی', flag: '🇰🇬' },
  { title: 'لائوسی', flag: '🇱🇦' },
  { title: 'لاتین', flag: '🌍' },
  { title: 'لتونی', flag: '🇱🇻' },
  { title: 'لیتوانیایی', flag: '🇱🇹' },
  { title: 'لوکزامبورگی', flag: '🇱🇺' },
  { title: 'مقدونی', flag: '🇲🇰' },
  { title: 'مالاگاسی', flag: '🇲🇬' },
  { title: 'مالایی', flag: '🇲🇾' },
  { title: 'مالایالام', flag: '🇮🇳' },
  { title: 'مالتی', flag: '🇲🇹' },
  { title: 'مائوری', flag: '🇳🇿' },
  { title: 'مراتی', flag: '🇮🇳' },
  { title: 'مغولی', flag: '🇲🇳' },
  { title: 'میانماری (برمه‌ای)', flag: '🇲🇲' },
  { title: 'نپالی', flag: '🇳🇵' },
  { title: 'نروژی', flag: '🇳🇴' },
  { title: 'نیانجا (چیچوا)', flag: '🇲🇼' },
  { title: 'اودیا (اوریه)', flag: '🇮🇳' },
  { title: 'پشتو', flag: '🇦🇫' },
  { title: 'فارسی', flag: '🇮🇷' },
  { title: 'لهستانی', flag: '🇵🇱' },
  { title: 'پرتغالی', flag: '🇵🇹' },
  { title: 'پنجابی', flag: '🇮🇳' },
  { title: 'رومانیایی', flag: '🇷🇴' },
  { title: 'روسی', flag: '🇷🇺' },
  { title: 'ساموآیی', flag: '🇼🇸' },
  { title: 'گیلیک اسکاتلندی', flag: '🏴' },
  { title: 'صربی', flag: '🇷🇸' },
  { title: 'سوتو', flag: '🇱🇸' },
  { title: 'شونا', flag: '🇿🇼' },
  { title: 'سندی', flag: '🇵🇰' },
  { title: 'سینهالی', flag: '🇱🇰' },
  { title: 'اسلواکی', flag: '🇸🇰' },
  { title: 'اسلوونیایی', flag: '🇸🇮' },
  { title: 'سومالیایی', flag: '🇸🇴' },
  { title: 'اسپانیایی', flag: '🇪🇸' },
  { title: 'سوندایی', flag: '🇮🇩' },
  { title: 'سواحیلی', flag: '🇰🇪' },
  { title: 'سوئدی', flag: '🇸🇪' },
  { title: 'تاگالوگ (فیلیپینی)', flag: '🇵🇭' },
  { title: 'تاجیکی', flag: '🇹🇯' },
  { title: 'تامیل', flag: '🇮🇳' },
  { title: 'تاتار', flag: '🇷🇺' },
  { title: 'تلوگو', flag: '🇮🇳' },
  { title: 'تایلندی', flag: '🇹🇭' },
  { title: 'ترکی', flag: '🇹🇷' },
  { title: 'ترکمنی', flag: '🇹🇲' },
  { title: 'اوکراینی', flag: '🇺🇦' },
  { title: 'اردو', flag: '🇵🇰' },
  { title: 'اویغوری', flag: '🇨🇳' },
  { title: 'ازبکی', flag: '🇺🇿' },
  { title: 'ویتنامی', flag: '🇻🇳' },
  { title: 'ولزی', flag: '🏴' },
  { title: 'خوسا', flag: '🇿🇦' },
  { title: 'ییدیش', flag: '🇮🇱' },
  { title: 'یوروبا', flag: '🇳🇬' },
  { title: 'زولو', flag: '🇿🇦' },
  {
    title: 'فست‌فود',
    icon: FastFoodIcon,
  },
  {
    title: 'قهوه',
    icon: CaffeIcon,
  },
  {
    title: 'گوشت‌خواری',
    icon: MeatIcon,
  },
  {
    title: 'گیاه‌خواری',
    icon: VegetarianIcon,
  },
  {
    title: 'نوشیدنی',
    icon: WineIcon,
  },
  {
    title: 'الکترونیک',
    icon: MusicIcon,
  },
  {
    title: 'پاپ',
    icon: MusicIcon,
  },
  {
    title: 'کلاسیک',
    icon: MusicIcon,
  },
  {
    title: 'سنتی',
    icon: MusicIcon,
  },
  {
    title: 'هیپ هاپ',
    icon: MusicIcon,
  },
  {
    title: 'راک',
    icon: MusicIcon,
  },
  {
    title: 'محلی',
    icon: MusicIcon,
  },
  {
    title: 'اسکیت',
    icon: SkateIcon,
  },
  {
    title: 'پاراگلایدر',
    icon: ParagliderIcon,
  },
  {
    title: 'تیراندازی',
    icon: ShootingIcon,
  },
  {
    title: 'غارنوردی',
    icon: CaveIcon,
  },
  {
    title: 'بدن سازی',
    icon: BodybuildingIcon,
  },
  {
    title: 'کاراته',
    icon: KarateIcon,
  },
  {
    title: 'فوتبال',
    icon: SoccerIcon,
  },
  {
    title: 'اسب سواری',
    icon: HorseIcon,
  },
  {
    title: 'تخته نرد',
    icon: BackgammonIcon,
  },
  {
    title: 'اسکواش',
    icon: SquashIcon,
  },
  {
    title: 'خرگوش',
    icon: RabbitIcon,
  },
  {
    title: 'شیر',
    icon: LionIcon,
  },
  {
    title: 'سگ',
    icon: DogIcon,
  },
  {
    title: 'سنجاب',
    icon: SquirrelIcon,
  },
  {
    title: 'همستر',
    icon: HamsterIcon,
  },
  {
    title: 'طوطی',
    icon: ParrotIcon,
  },
  {
    title: 'گربه',
    icon: CatIcon,
  },
  {
    title: 'قناری',
    icon: CanaryIcon,
  },
  {
    title: 'میمون',
    icon: MonkeyIcon,
  },
  {
    title: 'ماهی',
    icon: FishIcon,
  },
  {
    title: 'خوانندگی',
    icon: SingerIcon,
  },
  {
    title: 'نوازندگی',
    icon: PlayingIcon,
  },
  {
    title: 'طراحی',
    icon: DesignIcon,
  },
  {
    title: 'نویسندگی',
    icon: WritingIcon,
  },
  {
    title: 'طنزپردازی',
    icon: HumoristIcon,
  },
  {
    title: 'ترسناک',
    icon: MovieIcon,
  },
  {
    title: 'علمی تخیلی',
    icon: MovieIcon,
  },
  {
    title: 'انیمه',
    icon: MovieIcon,
  },
  {
    title: 'دام',
    icon: MovieIcon,
  },
  {
    title: 'هیجانی',
    icon: MovieIcon,
  },
  {
    title: 'اکشن',
    icon: MovieIcon,
  },
  {
    title: 'کمدی',
    icon: MovieIcon,
  },
  {
    title: 'عاشقانه',
    icon: MovieIcon,
  },
  {
    title: 'معمایی',
    icon: MovieIcon,
  },
  {
    title: 'کنسرت ها',
    icon: ConcertIcon,
  },
  {
    title: 'بازار ها',
    icon: MarketsIcon,
  },
  {
    title: 'کافه ها و رستوران ها',
    icon: RestaurantIcon,
  },
  {
    title: 'موزه ها و گالری ها',
    icon: MuseamIcon,
  },
  {
    title: 'جشنواره ها',
    icon: FestivalsIcon,
  },
  {
    title: 'تئاتر یا سینما',
    icon: TheaterIcon,
  },
  {
    title: 'پارک ها',
    icon: ParkIcon,
  },
  {
    title: 'مساجد یا کلیسا ها',
    icon: MosqueIcon,
  },
  {
    title: 'بازی ویدیویی',
    icon: GameIcon,
  },
  {
    title: 'بازی دورهمی',
    icon: GroupGameIcon,
  },
  {
    title: 'سفالگری',
    icon: PotteryIcon,
  },
  {
    title: 'باغبانی',
    icon: GardeningIcon,
  },
  {
    title: 'طبیعت گردی',
    icon: NatureTourIcon,
  },
  {
    title: 'تبادل فرهنگی',
    icon: CulturalExchangeIcon,
  },
  {
    title: 'قوم شناسی',
    icon: EthnologyIcon,
  },
  {
    title: 'کاوشگری',
    icon: ExplorationIcon,
  },
  {
    title: 'کشتی',
    icon: ShipIcon,
  },
  {
    title: 'مسافرت با قطار',
    icon: TrainIcon,
  },
  {
    title: 'کمپینگ',
    icon: CampingIcon,
  },
  {
    title: 'روستا گردی',
    icon: VillageTourIcon,
  },
  {
    title: 'فرهنگی',
    icon: CulturalIcon,
  },
  {
    title: 'قایق سواری',
    icon: BoatIcon,
  },
  {
    title: 'شنا',
    icon: SwimmingIcon,
  },
  {
    title: 'مسافرت با کشتی',
    icon: TravelingByShipIcon,
  },
  {
    title: 'صخره نوردی',
    icon: ClimbingIcon,
  },
  {
    title: 'دریا و ساحل',
    icon: SeeBeach,
  },
  {
    title: 'آفرود سواری',
    icon: OffroadIcon,
  },
  {
    title: 'دوچرخه سواری',
    icon: bicycle,
  },
  {
    title: 'ماهی گیری',
    icon: FishingIcon,
  },
  {
    title: 'حیات وحش',
    icon: WildlifeIcon,
  },
  {
    title: 'اماکن تاریخی',
    icon: HistoricalPlacesIcon,
  },
  {
    title: 'ماجراجویی',
    icon: AdventoreIcon,
  },
  {
    title: 'طبیعت',
    icon: NatureIcon,
  },
  {
    title: 'اسکی و برف',
    icon: SkiingIcon,
  },
  {
    title: 'خرید',
    icon: ShopIcon,
  },
  {
    title: 'کوله گردی',
    icon: BackpackingIcon,
  },
  {
    title: 'پیاده روی',
    icon: WalkingIcon,
  },
  {
    title: 'غذا و آشپزی',
    icon: FoodIcon,
  },
  { title: 'درون‌گرا', icon: Spirit },
  { title: 'برون‌گرا', icon: Spirit },
  { title: 'به طور منظم', icon: Sport },
  { title: 'بعضی‌وقت‌ها', icon: Sport },
  { title: 'خیلی کم', icon: Sport },
  { title: 'متاهل', icon: Marital },
  { title: 'مجرد', icon: Marital },
  { title: 'زن', icon: Gender },
  { title: 'مرد', icon: Gender },
  { title: 'سحرخیز', icon: AmountOfEarlyRisingSvg },
  { title: 'خواب‌آلود', icon: AmountOfEarlyRisingSvg },
  { title: 'آن‌تایم', icon: AmountOfEarlyRisingSvg },
  { title: 'به طور منظم', icon: Smoke },
  { title: 'بعضی‌وقت‌ها', icon: Smoke },
  { title: 'هرگز', icon: Smoke },
];
