export const iranProvinces = [
  { label: 'البرز', key: '1' },
  { label: 'اردبیل', key: '2' },
  { label: 'ایلام', key: '3' },
  { label: 'اصفهان', key: '4' },
  { label: 'آذربایجان غربی', key: '5' },
  { label: 'آذربایجان شرقی', key: '6' },
  { label: 'بوشهر', key: '7' },
  { label: 'تهران', key: '8' },
  { label: 'چهار محال و بختیاری', key: '10' },
  { label: 'خراسان جنوبی', key: '11' },
  { label: 'خراسان رضوی', key: '12' },
  { label: 'خراسان شمالی', key: '13' },
  { label: 'خوزستان', key: '14' },
  { label: 'زنجان', key: '15' },
  { label: 'سمنان', key: '16' },
  { label: 'سیستان و بلوچستان', key: '17' },
  { label: 'فارس', key: '18' },
  { label: 'قزوین', key: '19' },
  { label: 'قم', key: '20' },
  { label: 'کردستان', key: '21' },
  { label: 'کرمان', key: '22' },
  { label: 'کرمانشاه', key: '23' },
  { label: 'کهکیلویه و بویراحمد', key: '24' },
  { label: 'گلستان', key: '25' },
  { label: 'گیلان', key: '26' },
  { label: 'لرستان', key: '27' },
  { label: 'مازندران', key: '28' },
  { label: 'مرکزی', key: '29' },
  { label: 'هرمزگان', key: '30' },
  { label: 'همدان', key: '31' },
  { label: 'یزد', key: '32' },
];
