query GetBlockList {
  getBlockList {
    chats {
      id
      participants {
        id
        name
        username
        images
        isOnline
      }
      createdAt
      Message {
        id
        content
        sender {
          username
          name
          id
        }
        senderId
        createdAt
        read
      }
    }
    blacklists {
      id
      userId
      blockedId
      createdAt
    }
  }
}
