query GetChats {
  getChats {
    id
    searchType
    participants {
      id
      name
      username
      phoneNumber
      mainImage
      lastSeen
      isOnline
    }
    Message {
      sender {
        id
        name
        username
      }
      replyId
      reply {
        id
        content
        sender {
          id
          name
          username
        }
      }
      senderId
      read
      type
      url
      content
      id
      createdAt
    }
  }
}
query GetChat($chatId: String, $participantId: String) {
  getChat(chatId: $chatId, participantId: $participantId) {
    id
    searchType
    participants {
      id
      name
      username
      phoneNumber
      mainImage
      lastSeen
      isOnline
    }
    Message {
      sender {
        id
        name
        username
      }
      senderId
      read
      content
      id
      type
      url
      createdAt
      reply {
        id
        content
        type
        url
        sender {
          id
          name
        }
      }
    }
  }
}
