query GetChats {
  getChats {
    id
    searchType
    participants {
      id
      name
      username
      phoneNumber
      mainImages
      lastSeen
      isOnline
    }
    Message {
      sender {
        id
        name
        username
      }
      senderId
      read
      content
      id
      createdAt
    }
  }
}
query GetChat($chatId: String!) {
  getChat(chatId: $chatId) {
    id
    searchType
    participants {
      id
      name
      username
      phoneNumber
      mainImages
      lastSeen
      isOnline
    }
    Message {
      sender {
        id
        name
        username
      }
      senderId
      read
      content
      id
      createdAt
    }
  }
}
