query GetFavorite {
  getFavorite {
    chats {
      id
      createdAt
      Message {
        id
        content
        createdAt
        sender {
          id
          name
          username
        }
      }
      participants {
        id
        name
        username
        images
        isOnline
      }
    }
    favorites {
      id
      userId
      favoriteUserId
      createdAt
      updatedAt
    }
  }
}
