query GetMe {
  getMe {
    name
    username
    id
    avatar
    isOnline
    phoneNumber
    gender
    languages
    birthdate
    zodiacSign
    traveledToPlaces
    livedInPlaces
    province
    age
    city
    images
    travelInterests
    personalInterests
    mySpecialty
    bio
    maritalStatus
    smokeStatus
    spiritStatus
    sportsStatus
    lastSeen
    verified
    AmountOfEarlyRising
    plan {
      id
      title
      expireAt
      createdAt
      updatedAt
    }
  }
}
