query GetRequests {
  getRequests {
    id
    receiverId
    requesterId
    type
    createdAt
    updatedAt
    status
    requester {
      id
      name
      mainImages
    }
    receiver {
      id
      name
      mainImages
    }
  }
}
query GetRequest($requesterId: String!, $type: RequestType!) {
  getRequest(requesterId: $requesterId, type: $type) {
    id
    receiverId
    requesterId
    status
    type
    createdAt
    updatedAt
  }
}
