query GetUser($id: String!, $recommended: Boolean) {
  getUser(id: $id, recommended: $recommended) {
    id
    name
    username
    avatar
    isOnline
    phoneNumber
    gender
    languages
    birthdate
    zodiacSign
    traveledToPlaces
    livedInPlaces
    province
    age
    record
    city
    mainImage
    images
    travelInterests
    personalInterests
    mySpecialty
    bio
    maritalStatus
    smokeStatus
    spiritStatus
    sportsStatus
    lastSeen
    AmountOfEarlyRising
    createdAt
    planUse
  }
}
query RecommendedUsers {
  recommendedUsers {
    id
    name
    username
    isOnline
    avatar
    phoneNumber
    gender
    birthdate
    languages
    traveledToPlaces
    livedInPlaces
    province
    age
    zodiacSign
    city
    images
    mainImage
    travelInterests
    personalInterests
    mySpecialty
    bio
    record
    maritalStatus
    smokeStatus
    spiritStatus
    sportsStatus
    lastSeen
    AmountOfEarlyRising
    createdAt
    updatedAt
    deletedAt
    otp
    otpExpiresAt
    verified
    role
    score
    planUse
  }
}
