query GetUser($id: String!) {
  getUser(id: $id) {
    id
    name
    username
    avatar
    isOnline
    phoneNumber
    gender
    languages
    birthdate
    zodiacSign
    traveledToPlaces
    livedInPlaces
    province
    age
    city
    mainImage
    images
    travelInterests
    personalInterests
    mySpecialty
    bio
    maritalStatus
    smokeStatus
    spiritStatus
    sportsStatus
    lastSeen
    AmountOfEarlyRising
    createdAt
  }
}
